### ISSUE TITLE
V2 - Typed routes are adding paths outside of app dir when pressing save on file

### ISSUE THREAD

**Issue by sannajammeh** [expo/router#736]
### Which package manager are you using? (Yarn is recommended)

pnpm (known issues due to Metro)

### Summary

This is a weird one, but it appears typed routes which are not routes are being prepended when using `src/app` as the directory.

### Env info
```yaml
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.3.1 - ~/Library/pnpm/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 9.6.7 - ~/Library/pnpm/npm
      Watchman: 2023.02.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.0 => 49.0.0 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.1 => 0.72.1 
      react-native-web: ~0.19.6 => 0.19.6 
    Expo Workflow: managed
```

## Affected code in `.expo/types/router.d.ts`
```ts
 type StaticRoutes = `/` | `/(auth)/sign-in` | `/sign-in` | `/(tabs)/` | `/(tabs)` | `/(tabs)/profile` | `/profile` | `/(tabs)/search` | `/search` | `/badges/` | `/history/` | `/misc/achievement` | `/onboarding/` | `/onboarding/two` | `/screen-preview` | `/settings/faq/` | `/settings/` | `/settings/tos/` | `/Users/sannajammeh/code/chew/chew-mono-final/apps/mobile/src/features/recipe/player/StepsPlayer` | `/Users/sannajammeh/code/chew/chew-mono-final/apps/mobile/src/hooks/useControlledState`;
```

### Minimal reproducible example

https://github.com/sannajammeh/expo-49-test

To reproduce:
1. Install
2. Start it normally
3. Connect with expo go app
4. Press save on a file in components folder
5. Watch it get added to static paths
